### ISSUE TITLE
3d shape that looks identical to 2D in style?

### ISSUE THREAD

**Issue by coldformed** [thinwalled/cufsm-git#26]
I was thinking about explaining the 2D and 3D shape to a student. I was wondering if one version of the 3D shape, maybe the default without contours, could use the same colors and styles as the 2D shape. So the connection would be super clear that the 2D is just a slice of the 3D. In general I still find the 2D shape powerful, so helping new users to see the close connection between the two seems valuable.

**Comment by SJin24** [comment]
I tried it in this way:
One more item was added in the 3D Data pop-up menu. If this new item was selected, the 3D shape would be drawn in the 2D plotting style. The following contents are adjusted so that the 3D plotting looks much the same to the 2D shape: 1) scale factor, 2) default view direction, 3) colors of deformed and undeformed shapes, 4) line width, and 5) mesh density.
By default, it looks like this:
![image](https://github.com/thinwalled/cufsm-git/assets/120219986/e461fe2c-b50e-41f9-a974-3181bd1b8919)

If rotated, the 3D shape looks like the following:
![image](https://github.com/thinwalled/cufsm-git/assets/120219986/f1069a10-0baf-445a-aa53-474f7fed2012)
